name = "Judson Burmese Bible"
short_name = "JVB"
id = "myajvb"
license = "https://ebible.org/find/details.php?id=myajvb"
language = "mya"
data_source = "https://ebible.org/find/details.php?id=myajvb"

book_aliases = "my"
book_abbreviations = "my"

[books]
Gen = "ကမ္ဘာဦးကျမ်း"
Exod = "ထွက်မြောက်ရာကျမ်း"
Lev = "ဝတ်ပြုရာကျမ်း"
Num = "တောလည်ရာကျမ်း"
Deut = "တရားဟောရာကျမ်း"
Josh = "ယောရှုမှတ်စာ"
Judg = "တရားသူကြီးမှတ်စာ"
Ruth = "ရုသမှတ်စာ"
1Sam = "ဓမ္မရာဇဝင်ပထမစောင်"
2Sam = "ဓမ္မရာဇဝင်ဒုတိယစောင်"
1Kgs = "ရာဇဝင်ချုပ်ပထမစောင်"
2Kgs = "ရာဇဝင်ချုပ်ဒုတိယစောင်"
1Chr = "ရာဇဝင်ချုပ်ပထမစောင်"
2Chr = "ရာဇဝင်ချုပ်ဒုတိယစောင်"
Ezra = "ဧဇရမှတ်စာ"
Neh = "နေဟမိမှတ်စာ"
Esth = "ဧသတာမှတ်စာ"
Job = "ယောဘမှတ်စာ"
Ps = "ဆာလံကျမ်း"
Prov = "သုတ္တံကျမ်း"
Eccl = "ဒေသနာကျမ်း"
Song = "ရှောလမုန်သီချင်း"
Isa = "ဟေရှာယအနာဂတ္တိကျမ်း"
Jer = "ယေရမိအနာဂတ္တိကျမ်း"
Lam = "ယေရမိမြည်တမ်းကျမ်း"
Ezek = "ယေဇကျေလအနာဂတ္တိကျမ်း"
Dan = "ဒံယေလအနာဂတ္တိကျမ်း"
Hos = "ဟောရှေအနာဂတ္တိကျမ်း"
Joel = "ယောလအနာဂတ္တိကျမ်း"
Amos = "အာမုတ်အနာဂတ္တိကျမ်း"
Obad = "ဩဗဒိအနာဂတ္တိကျမ်း"
Jonah = "ယောနအနာဂတ္တိကျမ်း"
Mic = "မိက္ခာအနာဂတ္တိကျမ်း"
Nah = "နာဟုံအနာဂတ္တိကျမ်း"
Hab = "ဟဗက္ကုတ်အနာဂတ္တိကျမ်း"
Zeph = "ဇေဖနိအနာဂတ္တိကျမ်း"
Hag = "ဟဂ္ဂဲအနာဂတ္တိကျမ်း"
Zech = "ဇာခရိအနာဂတ္တိကျမ်း"
Mal = "မာလခိအနာဂတ္တိကျမ်း"
Matt = "မဿဲခရစ်ဝင်"
Mark = "မာကုခရစ်ဝင်"
Luke = "လုကာခရစ်ဝင်"
John = "ယောဟန်ခရစ်ဝင်"
Acts = "တမန်တော်ဝတ္ထု"
Rom = "ရောမဩဝါဒစာ"
1Cor = "ကောရိန္သုဩဝါဒစာပထမစောင်"
2Cor = "ကောရိန္သုဩဝါဒစာဒုတိယစောင်"
Gal = "ဂလာတိဩဝါဒစာ"
Eph = "ဧဖက်ဩဝါဒစာ"
Phil = "ဖိလိပ္ပိဩဝါဒစာ"
Col = "ကောလောသဲဩဝါဒစာ"
1Thess = "သက်သာလောနိတ်ဩဝါဒစာပထမစောင်"
2Thess = "သက်သာလောနိတ်ဩဝါဒစာဒုတိယစောင်"
1Tim = "တိမောသေဩဝါဒစာပထမစောင်"
2Tim = "တိမောသေဩဝါဒစာဒုတိယစောင်"
Titus = "တိတုဩဝါဒစာ"
Phlm = "ဖိလေမုန်ဩဝါဒစာ"
Heb = "ဟေဗြဲဩဝါဒစာ"
Jas = "ယာကုပ်ဩဝါဒစာ"
1Pet = "ပေတရုဩဝါဒစာပထမစောင်"
2Pet = "ပေတရုဩဝါဒစာဒုတိယစောင်"
1John = "ယောဟန်ဩဝါဒစာပထမစောင်"
2John = "ယောဟန်ဩဝါဒစာဒုတိယစောင်"
3John = "ယောဟန်ဩဝါဒစာတတိယစောင်"
Jude = "ယုဒဩဝါဒစာ"
Rev = "ဗျာဒိတ်ကျမ်း"
